name: Create and publish a Docker image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

concurrency: ci-${{ github.ref }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Static Analysis
        uses: pre-commit/action@v3.0.0

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests
        run: python -m pytest tests/ -s -v


  docker-build-jupyter:
    needs: [tests]
    uses: "./.github/workflows/docker_build.yml"
    secrets: inherit
    with:
      NOTEBOOK_TYPE: jupyter

  docker-build-rstudio:
    needs: [tests]
    uses: "./.github/workflows/docker_build.yml"
    secrets: inherit
    with:
      NOTEBOOK_TYPE: rstudio
